[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800

; --- Fix for ESP32-S3 upload issue ---
board_build.mcu = esp32s3
board_upload.use_1200bps_touch = false
board_upload.wait_for_upload_port = true

build_flags = 
    -I lib/kyber
    -O3
    -DWIFI_SSID="\"botnet\""
    -DWIFI_PASSWORD="\"123456789\""
    -DSERVER_URL="\"http://10.229.27.109:5000\""
    -DAUTH_ENDPOINT="\"/api/devices/device-provisioning/authenticate\""

lib_deps = 
    adafruit/Adafruit NeoPixel@^1.15.2
    links2004/WebSockets@^2.4.1
    bblanchon/ArduinoJson@^6.21.3